scrub_csv/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    # File processing views:
    # ex: /files/3/ -- This shows the files uploaded by Uploader id 3
    url(r'^(?P<uploader_id>[0-9]+)/$', views.index, name='index'),

    # ex: /files/3/new/ -- This lets the user upload a file
    url(r'^(?P<uploader_id>[0-9]+)/new/$', views.new, name='new'),

    # ex: /files/3/5/ -- This lets the user see relevant file info
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)/$',
        views.detail, name='detail'),

    # ex: /files/3/5/select/ -- This lets the user map file headers
    # to database fields
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)/select/$',
        views.select_fields, name='select_fields'),

    # ex: /files/3/5/process/ -- This processes the file and imports
    # the records to the database
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)/process/$',
        views.process, name='process'),

    # ex: /files/3/5/scrub/import_only -- This returns the scrubbing result for
    # the uploaded file, cleaning up if necessary
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)'
        r'/scrub/(?P<action>\w+)/$', views.scrub, name='scrub'),

    # ex: /files/3/5/download/ -- This downloads the corresponding generated
    # results file
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)'
        r'/download/(?P<file_type>\w+)/$', views.download, name='download'),

    # ex: /files/5/records/ -- This shows the processing result
    url(r'^(?P<uploader_id>[0-9]+)/(?P<document_id>[0-9]+)/records/$',
        views.records, name='records'),
]

scrubber/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'scrubber.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^files/', include('scrub_csv.urls', namespace="files")),
    url(r'^admin/', include(admin.site.urls)),
]

scrub_csv/models.py
from django.db import models
from django.contrib.auth.models import User


# A user is an uploader as well.
class Uploader(models.Model):
    user = models.OneToOneField(User)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.user.username


# A user can upload many documents...
class Document(models.Model):
    uploader = models.ForeignKey(Uploader)
    csvfile = models.FileField(upload_to='uploads/%Y/%m/%d',
                               verbose_name='file')
    row_count = models.PositiveIntegerField(default=0,
                                            verbose_name='rows in file')
    found_file = models.FileField(upload_to='downloads/%Y/%m/%d',
                                  verbose_name='found records',
                                  blank=True, null=True)
    not_found_file = models.FileField(upload_to='downloads/%Y/%m/%d',
                                      verbose_name='not found records',
                                      blank=True, null=True)
    upload_date = models.DateTimeField(auto_now_add=True,
                                       verbose_name="date uploaded")

    def __unicode__(self):
        timeformat = "%Y%m%d_%H%M%S"
        return u'%s_%s' % (str(self.uploader.id),
                           self.upload_date.strftime(timeformat))


# ...A document can have many rows (which can be permanent or just
# to scrub against, then deleted afterwards)...
class Row(models.Model):
    document = models.ForeignKey(Document)
    permanent = models.BooleanField(default=True)

    def __unicode__(self):
        return str(self.document.id) + ": " + str(self.id)


# ...and a row can have many records (key:value)
class Record(models.Model):
    row = models.ForeignKey(Row)
    doc_key = models.CharField(max_length=200)
    doc_value = models.CharField(max_length=200, default="")

    def __unicode__(self):
        return self.doc_key + ": " + self.doc_value

scrub_csv/forms.py
# -*- coding: utf-8 -*-
from django import forms


class DocumentForm(forms.Form):
    csvfile = forms.FileField(
        label='Select a CSV file for upload',
        widget=forms.FileInput(attrs={'class': 'file'})
    )

scrub_csv/views.py
# TODO: Remove HttpResponse after removing method stubs
from django.http import HttpResponseRedirect, HttpResponse
# XXX: In case the path to the files is needed in some other way, uncomment:
# from django.conf import settings
from django.contrib import messages
from django.db.models import Q
from django.shortcuts import get_object_or_404, render, render_to_response
from django.core.files import File
from django.core.urlresolvers import reverse


import functions

from .models import Uploader, Document, Row, Record
import unicodecsv


def index(request, uploader_id):
    u = get_object_or_404(Uploader, pk=uploader_id)
    latest_document_list = Document.objects.filter(uploader=u).\
        order_by('-upload_date')[:5]
    context = {
        'uploader_id': u.id,
        'latest_document_list': latest_document_list,
    }
    return render(request, 'files/index.html', context)


def new(request, uploader_id):
    from django.template import RequestContext
    from .forms import DocumentForm
    import datetime

    uploader = get_object_or_404(Uploader, pk=uploader_id)

    # Handle file upload
    if request.method == 'POST':
        form = DocumentForm(request.POST, request.FILES)
        if form.is_valid():
            newdoc = Document(uploader=uploader,
                              csvfile=request.FILES['csvfile'],
                              upload_date=datetime.datetime.now())
            newdoc.save()

            # Redirect to the document list after POST
            redirect_context = {
                'uploader_id': uploader.id,
                'document_id': newdoc.id
            }
            return HttpResponseRedirect(
                reverse('files:detail', kwargs=redirect_context)
            )
    else:
        form = DocumentForm()  # A empty, unbound form

    # Render list page with the documents and the form
    context = {
        'form': form,
        'uploader_id': uploader.id,
    }
    return render_to_response('files/new.html', context,
                              context_instance=RequestContext(request))


def detail(request, uploader_id, document_id):
    uploader = get_object_or_404(Uploader, pk=uploader_id)
    document = get_object_or_404(Document, pk=document_id)

    context = {
        'document': document,
        'uploader_id': uploader.id,
    }
    return render(request, 'files/detail.html', context)


def records(request, uploader_id, document_id):
    response = "You're looking at the records of document %s."
    return HttpResponse(response % document_id)


def select_fields(request, uploader_id, document_id):
    uploader = get_object_or_404(Uploader, pk=uploader_id)
    document = get_object_or_404(Document, pk=document_id)

    f = open(document.csvfile.path)
    csv_f = ""
    error = ""
    get_lines = 3

    try:
        sample = f.readline()
        sniffer = unicodecsv.Sniffer()
        dialect = sniffer.sniff(sample, delimiters=";,\t")
    except:
        # The file failed to be parsed as a valid CSV file.
        print sample
        error = "The file doesn't appear to be a valid CSV file."
        messages.error(request, error)
        redirect_context = {
            'document': document,
            'uploader_id': uploader.id,
        }
        return HttpResponseRedirect(
            reverse('files:detail', kwargs=redirect_context)
        )
    else:
        has_header = sniffer.has_header(sample)
        f.seek(0)
        csv_f = unicodecsv.reader(f, dialect)

        number_rows = sum(1 for row in csv_f)
        document.row_count = number_rows
        document.save()

        f.seek(0)
        content = list()
        for line in range(0, get_lines):
            try:
                content.append(csv_f.next())
            except:
                pass
        line_count = len(content)
    finally:
        f.close()

    context = {
        'document': document,
        'uploader_id': uploader.id,
        'has_header': has_header,
        'content': content,
        'line_count': line_count,
        'error_message': error
    }
    return render(request, 'files/select.html', context)


def process(request, uploader_id, document_id):
    u = get_object_or_404(Uploader, pk=uploader_id)
    d = get_object_or_404(Document, pk=document_id)
    try:
        # Get file processing options:
        perform_action = request.POST.get('action')
        has_header_row = request.POST.get('has_header_row', False)
        has_header_row = True if has_header_row else False
        errors = list()

        if perform_action == 'import_only':
            permanent = True
        else:
            permanent = False

        # Get all the column options:
        column_actions = list()
        ignored_columns = 0
        total_columns = int(request.POST.get('csv_columns'))
        column_positions = range(1, total_columns + 1)
        for column_number in column_positions:
            action = dict()
            current_col = "column_choice" + str(column_number)
            current_choice = request.POST[current_col]
            action["set_key"] = current_choice

            if current_choice == "select":
                # get key value from post
                action["value"] = request.POST.get("key" + str(column_number))
            elif current_choice == "header":
                if has_header_row:
                    action["value"] = ""
                else:
                    action["set_key"] = "ignore"
                    action["value"] = False
                    ignored_columns += 1
            elif current_choice == "custom":
                action["value"] = request.POST.get(
                    "custom_key" + str(column_number))
            elif current_choice == "ignore":
                action["value"] = False
            else:
                raise ValueError("An incorrect option was passed.")
            column_actions.append(action)

        if ignored_columns >= total_columns:
            # Houston, we have a problem.
            err_text = "Cannot import the file, all columns are set to ignore."
            errors.append(err_text)
        else:
            # Open and process CSV file:
            row_counter = 0
            records_ok = 0
            records_ignored = 0
            csv_header = list()

            with open(d.csvfile.path) as f:
                csv_f = unicodecsv.reader(f)

                # Skip the header row from importing:
                if has_header_row:
                    csv_header = csv_f.next()

                for row in csv_f:
                    row_counter += 1

                    # Create a new Row object and save it:
                    try:
                        db_row = Row(document_id=d.id, permanent=permanent)
                        db_row.save()
                    except Exception as e:
                        raise e

                    # Now create and save new Records with current Row id:
                    for pos in [x - 1 for x in column_positions]:
                        if (column_actions[pos]["set_key"] == "select" or
                                column_actions[pos]["set_key"] == "custom"):
                            temp_key = column_actions[pos]["value"]
                        elif column_actions[pos]["set_key"] == "header":
                            temp_key = csv_header[pos]
                        elif column_actions[pos]["set_key"] == "ignore":
                            records_ignored += 1
                            continue
                        else:
                            pass  # for now. Proper error handling is needed.

                        temp_key = functions.clean_key(temp_key)
                        doc_key = functions.validate_key(temp_key)

                        try:
                            # If the record to be saved represents an e-mail
                            # (but is not mistakenly selected as email_md5)
                            # also save it encoded as md5:
                            if doc_key == "email":
                                if (functions.is_email(row[pos]) and not
                                        functions.is_md5(row[pos])):
                                    # Save the additional record:
                                    doc_value = functions.string_to_md5(
                                        row[pos])
                                    db_record = Record(row_id=db_row.id,
                                                       doc_key="email_md5",
                                                       doc_value=doc_value)
                                    db_record.save()
                                    records_ok += 1
                                elif functions.is_md5(row[pos]):
                                    # Proceed with normal save after correcting
                                    # wrong selection:
                                    doc_key = "email_md5"
                                else:
                                    # The value is not md5, but is not a valid
                                    # e-mail address either.
                                    pass

                            db_record = Record(row_id=db_row.id,
                                               doc_key=doc_key,
                                               doc_value=row[pos])
                            db_record.save()
                        except Exception as e:
                            raise e
                        else:
                            records_ok += 1
                # endfor
            # endwith
    except Exception as e:
        raise e
        # Redisplay the document select form.

        return render(request, 'files/select.html', {
            'uploader_id': u.id,
            'document': d,
            'error_message': "An exception was raised.",
        })
    else:
        response_kwargs = {
            'uploader_id': u.id,
            'document_id': d.id,

scrub_csv/templates/files/detail.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
{% endblock %}

{% block title %}
File details
{% endblock %}

{% block content %}
<div class="row">
    You're looking at file: <strong>{{ document.csvfile.name }} - {{ document.csvfile.name }}</strong>
</div>
<div class="row">
{% if document.row_set.all %}
    <ul>
    {% for row in document.row_set.all %}
        {% for record in row.record_set.all %}
            <li>{{ record.doc_key }}: {{ record.doc_value }}</li>
        {% endfor %}
    {% endfor %}
    </ul>
{% else %}
    <p>This file doesn't appear to have been processed yet. <a href="{% url 'files:select_fields' uploader_id document.id %}">Do it?</a>
{% endif %}
</div>
<div class="row">
    <p><a href="{% url 'files:index' uploader_id %}">Go back to file index page.</a></p>
</div>
{% endblock %}

{% block bootstrap3_extra_script %}
{% endblock %}

scrub_csv/templates/files/index.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
{% endblock %}

{% block title %}
Uploaded documents list
{% endblock %}

{% block content %}
<div class="row">
{% if latest_document_list %}
    <p>Here are the latest files that you've uploaded:</p>
    <div class="list-group">
        {% for document in latest_document_list %}
            <a href="{% url 'files:detail' uploader_id document.id %}" class="list-group-item">
                {{ document }} - {{ document.csvfile.name }}
            </a>
        {% endfor %}
    </div>
    <p>
        You can upload a new file <a href="{% url 'files:new' uploader_id %}">here</a>.
    </p>
{% else %}
    <p>
        No uploaded files are available. <a href="{% url 'files:new' uploader_id %}">Add a new one?</a>
    </p>
{% endif %}
</div>
{% endblock%}

{% block bootstrap3_extra_script %}
{% endblock %}

scrub_csv/templates/files/new.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
    <link href="{% static 'scrub_csv/bootstrap-fileinput/css/fileinput.min.css' %}" media="all" rel="stylesheet" type="text/css" />
{% endblock %}

{% block title %}Upload a file{% endblock %}
{% block content %}
<div class="row">
    <form role="form" class="form-horizontal" action="{% url 'files:new' uploader_id %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <p>{{ form.non_field_errors }}</p>
        <p>{{ form.csvfile.label_tag }} {{ form.csvfile.help_text }}</p>
        <p>
            {{ form.csvfile.errors }}
            {{ form.csvfile }}
        </p>
    </form>
</div>
<div class="row">
    <p><a href="{% url 'files:index' uploader_id %}">Go back to file index page.</a></p>
</div>
{% endblock%}

{% block bootstrap3_extra_script %}
    <script src="{% static 'scrub_csv/bootstrap-fileinput/js/fileinput.min.js' %}"></script>
    <!-- optionally if you need translation for your language then include 
    locale file as mentioned below -->
    <!--
    <script src="{% static 'scrub_csv/bootstrap-fileinput/js/fileinput_locale_es.js' %}"></script>
    -->
{% endblock %}

scrub_csv/templates/files/process.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
{% endblock %}

{% block title %}
{% endblock %}

{% block content %}
{% endblock %}

{% block bootstrap3_extra_script %}
{% endblock %}

scrub_csv/templates/files/scrub.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block title %}File import results{% endblock %}
{% block content %}
<div class="row app-results">
    <div class="col-md-3">
        <h3>The uploaded file has been scrubbed.</h3>
    </div>
    <div class="col-md-9">
        {% ifequal action "import_only" %}
            <p>
                The file's records have been imported, you can now return to the
                file index page.
            </p>
        {% else %}
            <p>
                The file's records have been temporarily imported and scrubbed
                against the database; after scrubbing, the records 
                {% ifequal action "scrub_save" %}have been saved to the
                database.{% else %}have been discarded.{% endifequal %}
            </p>
            <p>
                You can download the resulting scrub files below:
            </p>
            {% if document.found_file %}
            <p>
                <a href="{% url 'files:download' uploader_id document.id "found_file" %}">Records found in database</a>
            </p>
            {% endif %}
            {% if document.not_found_file %}
            <p>
                <a href="{% url 'files:download' uploader_id document.id "not_found_file" %}">Records missing from database</a>
            </p>
            {% endif %}
        {% endifequal %}
    </div>
</div>
<div class="row">
    <p><a href="{% url 'files:index' uploader_id %}">Go back to file index page.</a></p>
</div>
{% endblock %}

scrub_csv/templates/files/select.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap3 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_extra_head %}
{% endblock %}

{% block title %}
Select the file's header fields
{% endblock %}

{% block content %}
    <div class="row">  
        <p>
            Please map each column in the file <strong>{{ document }}</strong>
            to a field for processing.
        <p>
    </div> 
    {% if not error_message %}
    <div class="row">
        <form role="form" class="form-horizontal" action="{% url 'files:process' uploader_id document.id %}" method="post">
        <fieldset>
        <!-- Form Name -->
        <legend>File options</legend>

        {% csrf_token %}
        <input type="hidden" name="csv_columns" value="{{ content.0|length }}">
        <!-- File options group -->
        <div class="form-group">
            <label class="col-md-4 control-label" for="action">What would you like to do with this file?</label>
            <div class="col-md-8">
                <div class="radio">
                    <label for="action_scrub_save">
                        <input name="action" id="action_scrub_save" value="scrub_save" checked="checked" type="radio">
                        Scrub against database, save records for future use.
                    </label>
                </div>
                <div class="radio">
                    <label for="action_scrub_only">
                        <input name="action" id="action_scrub_only" value="scrub_only" type="radio">
                        Scrub against database, but discard the records.
                  </label>
                </div>
                <div class="radio">
                    <label for="action_import_only">
                        <input name="action" id="action_import_only" value="import_only" type="radio">
                        Do not return a scrubbed file, just import the records to the database.
                    </label>
                </div>
            </div>
        </div>

        <div class="file-details">
            <p>
                Showing you the first {{ line_count }} line(s) of the file to 
                help you map each field.
            </p>
            <p>Now, please select one of the following for each column:</p>
            <ul>
            {% if existing_keys_list %}
                <li>An existing field from the database</li>
            {% endif %}
                <li>Use the file's header, if available (if not, the column will be ignored)</li>
                <li>A custom field name</li>
                <li>Ignore this column (do not import it to the database)</li>
            </ul>
        </div>

        <div class="file-table table-responsive">
            <table id="csvfile" class="table table-bordered">
                <thead>
                    <tr>
                    {% for column in content.0 %}
                        <th>Column #{{ forloop.counter }} Key</th>
                    {% endfor %}
                    </tr>
                    <tr>
                    {% for column in content.0 %}
                        <td>
                        <!-- Column options -->
                            <div class="form-group">
                                <div class="col-md-6 column-radio-group{{ forloop.counter }}">
                                {% if existing_keys_list %}
                                    <div class="radio">
                                        <label for="column_choice_select{{ forloop.counter }}">
                                            <input name="column_choice{{ forloop.counter }}" id="column_choice_select{{ forloop.counter }}" type="radio" value="select">
                                            Existing key
                                        </label>
                                        <select id="existing_key{{ forloop.counter }}" name="key{{ forloop.counter }}" class="form-control">
                                            <option value="">Select a field</option>
                                        {% for key in existing_keys_list %}
                                            <option value="{{ key }}">{{ key }}</option>
                                        {% endfor %}
                                        </select>
                                    </div>
                                {% endif %}
                                    <div class="radio">
                                        <label for="column_choice_header{{ forloop.counter }}">
                                            <input name="column_choice{{ forloop.counter }}" id="column_choice_header{{ forloop.counter }}" value="header" type="radio" checked="checked" >
                                            Use header as key
                                        </label>
                                    </div>
                                    <div class="radio">
                                        <label for="column_choice_custom{{ forloop.counter }}">
                                            <span class="input-group-addon">     
                                                <input name="column_choice{{ forloop.counter }}" id="column_choice_custom{{ forloop.counter }}" value="custom" type="radio">     
                                            </span>
                                        </label>
                                        <input id="custom_key{{ forloop.counter }}" name="custom_key{{ forloop.counter }}" class="form-control" placeholder="Enter custom name" type="text">
                                    </div>
                                    <div class="radio">
                                        <label for="column_choice_ignore{{ forloop.counter }}">
                                            <input name="column_choice{{ forloop.counter }}" id="column_choice_ignore{{ forloop.counter }}" value="ignore" type="radio">
                                            Ignore column (do not import)
                                        </label>
                                    </div>
                                </div>
                            </div>
                        </td>
                    {% endfor %}
                    </tr>
                </thead>
                <tbody>
                {% for row in content %}
                    <tr{% if forloop.first %} class="info"{% endif %}>
                    {% for item in row %}
                        <td>{{ item }}</td>
                    {% endfor %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div><!--/.row-->
    <div class="row">
        <div class="file-analysis">
            <p>
                Upon analysis, the first row of the file (highlighted in blue) {% if has_header %}appears{% else %}does not appear{% endif %} to be a header row. (This could be wrong, though.)<br/>
            </p>
            <p>
                Please confirm below:
            </p>
            <div class="form-group">
                <label class="col-md-4 control-label" for="has_header_row">The file does have a header row</label>
                <div class="col-md-8">
                    <div class="checkbox">
                        <label for="has_header_row">
                            <input name="has_header_row" id="has_header_row" value="1" type="checkbox"{% if has_header %} checked="checked"{% endif %}>
                            (Check/uncheck as needed)
                        </label>
                    </div>
                </div>
            </div>
        </div>
        {% buttons submit="Process file" reset="Cancel "%}{% endbuttons %}
        </fieldset>
        </form>
    </div><!--/.row-->
    {% else %}
    <div class="row">
        <p><strong>{{ error_message }}</strong></p>
    </div>
    {% endif %}
    <p><a href="{% url 'files:detail' uploader_id document.id %}">Go back to file details page.</a></p>
{% endblock %}

{% block bootstrap3_extra_script %}
<script>
$(function () {
    /* Column options */
    function reset_fields(index) {
        $('#select_key' + index).hide();
        $('#custom_key' + index).prop("disabled", true);
    }

    $("div[class*='column-radio-group']").each(function( index ) {
        reset_fields(index + 1);
    });

    $("input[name^='column_choice']").change(
        function (e) {
            column_num = $(this).attr("name").match(/\d+$/)[0];
            reset_fields(column_num);
            if ($(this).is(":checked")) {
                switch($(this).val()) {
                    case "select":
                        // Click on 'select existing key':
                        $('#select_key' + column_num).show().focus();
                        break;
                    case "header":
                        // Click on 'use header as key':
                        break;
                    case "custom":
                        // Click on 'enter custom name':
                        $('#custom_key' + column_num).prop("disabled", false).focus();
                        break;
                    case "ignore":
                        // Click on 'ignore column':
                        break;
                    default:
                        false
                }
            }
        });            
});
</script>
{% endblock %}